server:
    port: 8083
  spring:
    application:
      name: user-service
    datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:7072/train_db}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:password}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}