services:
  postgres:
    image: postgres:15
    ports:
      - "7072:7072"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railway_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres
    command: start-dev
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KEYCLOAK_URL: http://keycloak:8080
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - postgres
      - keycloak
      - eureka-server
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - postgres
      - eureka-server
  train-service:
    build: ./train-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/train_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - postgres
      - eureka-server
  booking-service:
    build: ./booking-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KAFKA_BROKER_URL: kafka:9092
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
    depends_on:
      - postgres
      - kafka
      - eureka-server
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - auth-service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  postgres_data: